import os
from dotenv import load_dotenv

load_dotenv()

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
DATABASE_URL = os.getenv("DATABASE_URL", "")

# Daftar 24 OPD Pemda DIY dengan Multi-Keywords Populer
OPDS = [
    {
        "id": "dinkes",
        "nama": "Dinas Kesehatan DIY",
        "news_queries": [
            "Dinas Kesehatan DIY",
            "Dinkes Jogja",
            "Pelayanan Kesehatan DIY",
            "Puskesmas Yogyakarta",
            "Rumah Sakit Jogja antrean",
            "Kasus DBD DIY Dinkes",
        ],
        "maps_query": "Dinas Kesehatan Daerah Istimewa Yogyakarta",
        "twitter_query": "Dinkes DIY OR Dinkes Jogja",
    },
    {
        "id": "dinsos",
        "nama": "Dinas Sosial DIY",
        "news_queries": [
            "Dinas Sosial DIY",
            "Dinsos Jogja",
            "Bansos DIY Jogja",
            "Penanganan Pengemis Jogja Dinsos",
            "Panti Sosial Yogyakarta",
            "Bantuan Sosial Pemda DIY",
        ],
        "maps_query": "Dinas Sosial Daerah Istimewa Yogyakarta",
        "twitter_query": "Dinsos DIY OR Dinsos Jogja",
    },
    {
        "id": "dishub",
        "nama": "Dinas Perhubungan DIY",
        "news_queries": [
            "Dinas Perhubungan DIY",
            "Dishub Jogja",
            "Trans Jogja pelayanan",
            "Parkir liar Yogyakarta",
            "Kemacetan Jogja Dishub",
            "Lalu Lintas Malioboro Dishub",
        ],
        "maps_query": "Dinas Perhubungan DIY Babarsari",
        "twitter_query": "Dishub DIY OR Dishub Jogja OR Trans Jogja",
    },
    {
        "id": "dispar",
        "nama": "Dinas Pariwisata DIY",
        "news_queries": [
            "Dinas Pariwisata DIY",
            "Dispar Jogja",
            "Wisata Yogyakarta keluhan",
            "Tarif parkir Malioboro",
            "Wisatawan Jogja liburan",
            "Destinasi wisata DIY Dispar",
        ],
        "maps_query": "Dinas Pariwisata DIY Malioboro",
        "twitter_query": "Dispar DIY OR Pariwisata Jogja",
    },
    {
        "id": "dikpora",
        "nama": "Dinas Pendidikan, Pemuda dan Olahraga DIY",
        "news_queries": [
            "Dikpora DIY",
            "Dinas Pendidikan DIY",
            "PPDB Jogja Dikpora",
            "Zonasi sekolah DIY",
            "Gedung sekolah rusak Jogja",
            "Beasiswa DIY Dikpora",
        ],
        "maps_query": "Dinas Dikpora DIY",
        "twitter_query": "Dikpora DIY OR Disdikpora Jogja",
    },
    {
        "id": "pupesdm",
        "nama": "Dinas PUP-ESDM DIY",
        "news_queries": [
            "Dinas PUP ESDM DIY",
            "PUPR Jogja jalan rusak",
            "Perbaikan jalan DIY",
            "Drainase banjir Yogyakarta",
            "Tambang pasir Merapi ESDM",
            "Infrastruktur jalan Pemda DIY",
        ],
        "maps_query": "Dinas PUP ESDM DIY Yogyakarta",
        "twitter_query": "PUP ESDM DIY OR Jalan Rusak Jogja",
    },
    {
        "id": "dlhk",
        "nama": "Dinas Lingkungan Hidup dan Kehutanan DIY",
        "news_queries": [
            "DLHK DIY",
            "Dinas Lingkungan Hidup DIY",
            "Sampah Jogja TPST Piyungan",
            "Darurat sampah Yogyakarta",
            "Pencemaran sungai Jogja DLHK",
            "Ruang Terbuka Hijau DIY",
        ],
        "maps_query": "DLHK DIY Yogyakarta",
        "twitter_query": "DLHK DIY OR Sampah Jogja",
    },
    {
        "id": "diskopukm",
        "nama": "Dinas Koperasi dan UKM DIY",
        "news_queries": [
            "Dinas Koperasi UKM DIY",
            "Diskop UKM Jogja",
            "UMKM Yogyakarta binaan",
            "Bantuan modal UMKM DIY",
            "SiBakul Jogja",
        ],
        "maps_query": "Dinas Koperasi UKM DIY Yogyakarta",
        "twitter_query": "Diskop UKM DIY OR SiBakul Jogja",
    },
    {
        "id": "disperindag",
        "nama": "Dinas Perindustrian dan Perdagangan DIY",
        "news_queries": [
            "Disperindag DIY",
            "Dinas Perindustrian Perdagangan DIY",
            "Harga beras pasar Jogja Disperindag",
            "Operasi pasar murah DIY",
            "Bahan pokok Jogja Disperindag",
        ],
        "maps_query": "Dinas Perindustrian Perdagangan DIY Yogyakarta",
        "twitter_query": "Disperindag DIY OR Pasar Murah Jogja",
    },
    {
        "id": "dpmptsp",
        "nama": "Dinas Penanaman Modal dan PTSP DIY",
        "news_queries": [
            "DPMPTSP DIY",
            "Dinas Perizinan DIY",
            "Izin usaha Jogja DPMPTSP",
            "Investasi DIY Yogyakarta",
            "Pelayanan izin OSS Jogja",
        ],
        "maps_query": "DPMPTSP DIY Yogyakarta",
        "twitter_query": "DPMPTSP DIY OR Perizinan Jogja",
    },
    {
        "id": "disnakertrans",
        "nama": "Dinas Tenaga Kerja dan Transmigrasi DIY",
        "news_queries": [
            "Disnakertrans DIY",
            "Dinas Tenaga Kerja DIY",
            "UMR UMP Jogja Disnakertrans",
            "Job Fair Disnakertrans DIY",
            "Pelatihan kerja BLK Jogja",
        ],
        "maps_query": "Disnakertrans DIY Yogyakarta",
        "twitter_query": "Disnakertrans DIY OR UMR Jogja",
    },
    {
        "id": "satpolpp",
        "nama": "Satuan Polisi Pamong Praja DIY",
        "news_queries": [
            "Satpol PP DIY",
            "Satpol PP Jogja razia",
            "Penertiban PKL Malioboro",
            "Ketertiban umum Yogyakarta",
            "Satpol PP jaga malam Jogja",
        ],
        "maps_query": "Satuan Polisi Pamong Praja DIY",
        "twitter_query": "Satpol PP DIY OR Satpol PP Jogja",
    },
    {
        "id": "diskominfo",
        "nama": "Dinas Komunikasi dan Informatika DIY",
        "news_queries": [
            "Diskominfo DIY",
            "Dinas Kominfo DIY",
            "Wifi publik Jogja Kominfo",
            "SPBE Pemda DIY",
            "Aplikasi Jogja Smart Province",
        ],
        "maps_query": "Diskominfo DIY Danurejan",
        "twitter_query": "Diskominfo DIY OR Kominfo Jogja",
    },
    {
        "id": "disbud",
        "nama": "Dinas Kebudayaan DIY",
        "news_queries": [
            "Dinas Kebudayaan DIY",
            "Kundha Kabudayan Jogja",
            "Cagar budaya Yogyakarta",
            "Festival kebudayaan DIY",
            "Danais kebudayaan Jogja",
        ],
        "maps_query": "Dinas Kebudayaan DIY",
        "twitter_query": "Disbud DIY OR Kundha Kabudayan",
    },
    {
        "id": "dispursip",
        "nama": "Dinas Perpustakaan dan Arsip Daerah DIY",
        "news_queries": [
            "DPAD DIY",
            "Grhatama Pustaka Yogyakarta",
            "Perpustakaan Daerah DIY",
            "Layanan arsip DIY",
            "Literasi baca Jogja DPAD",
        ],
        "maps_query": "Grhatama Pustaka DPAD DIY",
        "twitter_query": "DPAD DIY OR Grhatama Pustaka",
    },
    {
        "id": "dispertaru",
        "nama": "Dinas Pertanahan dan Tata Ruang DIY",
        "news_queries": [
            "Dispertaru DIY",
            "Tata Ruang Yogyakarta",
            "Tanah Kas Desa Jogja Dispertaru",
            "Sultan Ground Jogja",
            "Izin pemanfaatan tanah DIY",
        ],
        "maps_query": "Dispertaru DIY Yogyakarta",
        "twitter_query": "Dispertaru DIY OR Tanah Kas Desa",
    },
    {
        "id": "dispertan",
        "nama": "Dinas Pertanian dan Ketahanan Pangan DIY",
        "news_queries": [
            "Dinas Pertanian Ketahanan Pangan DIY",
            "DPKP DIY",
            "Gagal panen DIY",
            "Pupuk subsidi petani Jogja",
            "Ketahanan pangan Yogyakarta",
        ],
        "maps_query": "Dinas Pertanian Ketahanan Pangan DIY",
        "twitter_query": "DPKP DIY OR Pertanian Jogja",
    },
    {
        "id": "dkp",
        "nama": "Dinas Kelautan dan Perikanan DIY",
        "news_queries": [
            "Dinas Kelautan Perikanan DIY",
            "DKP DIY",
            "Nelayan Sadeng Baron DIY",
            "Pelabuhan perikanan Gesing Jogja",
            "Budidaya ikan air tawar DIY",
        ],
        "maps_query": "Dinas Kelautan dan Perikanan DIY",
        "twitter_query": "DKP DIY OR Nelayan Jogja",
    },
    {
        "id": "dp3ap2",
        "nama": "Dinas Pemberdayaan Perempuan, Perlindungan Anak dan Pengendalian Penduduk DIY",
        "news_queries": [
            "DP3AP2 DIY",
            "Perlindungan anak Yogyakarta",
            "Kekerasan perempuan DIY",
            "Stunting Jogja DP3AP2",
        ],
        "maps_query": "DP3AP2 DIY Yogyakarta",
        "twitter_query": "DP3AP2 DIY",
    },
    {
        "id": "sekda",
        "nama": "Sekretariat Daerah / Biro-biro",
        "news_queries": [
            "Sekretariat Daerah DIY",
            "Sekda DIY Kepatihan",
            "Biro Tata Pemerintahan DIY",
            "Biro Hukum Pemda DIY",
        ],
        "maps_query": "Sekretariat Daerah DIY Kepatihan",
        "twitter_query": "Setda DIY OR Pemda DIY",
    },
    {
        "id": "paniradya",
        "nama": "Paniradya Kaistimewan",
        "news_queries": [
            "Paniradya Kaistimewan DIY",
            "Dana Keistimewaan Jogja Danais",
            "Alokasi Danais DIY Paniradya",
        ],
        "maps_query": "Paniradya Kaistimewan Yogyakarta",
        "twitter_query": "Paniradya Kaistimewan OR Danais Jogja",
    },
    {
        "id": "dprd",
        "nama": "Sekretariat DPRD DIY",
        "news_queries": [
            "DPRD DIY Yogyakarta",
            "Komisi DPRD DIY",
            "Sidang paripurna DPRD DIY",
            "Aspirasi warga DPRD DIY",
        ],
        "maps_query": "DPRD DIY Malioboro",
        "twitter_query": "DPRD DIY",
    },
    {
        "id": "inspektorat",
        "nama": "Inspektorat DIY",
        "news_queries": [
            "Inspektorat DIY Yogyakarta",
            "Audit ASN Pemda DIY",
            "Pengawasan korupsi Pemda DIY",
        ],
        "maps_query": "Inspektorat DIY Yogyakarta",
        "twitter_query": "Inspektorat DIY",
    },
    {
        "id": "badan_daerah",
        "nama": "Badan-badan Daerah DIY",
        "news_queries": [
            "Bappeda DIY perencanaan",
            "BPBD DIY bencana erupsi longsor",
            "BPKAD DIY aset daerah",
            "BPSDM DIY pelatihan ASN",
        ],
        "maps_query": "Bappeda DIY Yogyakarta",
        "twitter_query": "BPBD DIY OR Bappeda DIY",
    },
]